#!/bin/sh

NAME='farmersnest'
DJANGODIR=/nestroot/nest_3_6_4/farmersnest
SOCKFILE=/nestroot/nest_3_6_4/run/gunicorn.sock
USER=nestuser
GROUP=nestgroup
NUM_WORKERS=3
DJANGO_SETTINGS_MODULE=farmersnest.settingsprod
DJANGO_WSGI_MODULE=farmersnest.wsgi
TIMEOUT=120

cd $DJANGODIR
source /nestroot/nest_3_6_4/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

exec /nestroot/nest_3_6_4/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --timeout $TIMEOUT \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=-
