# Generated by Django 2.2.14 on 2020-12-09 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('shipped', 'Shipped'), ('arrived', 'Arrived'), ('notpaid', 'Notpaid')], default='ordered', max_length=20),
        ),
    ]
